name: PyPi Publisher

on:
    push:
        tags:
            - 'v*'

jobs:
    build-n-publish:
        name: Build and publish Python package to PyPi
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@master
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                python-version: 3.7
            - name: Build binary tarball
              run: python setup.py bdist_wheel
            - name: Build source tarball
              run: python setup.py sdist --formats=gztar,zip
            - name: Publish artifacts to PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                password: ${{ secrets.PYPI_PASSWORD }}
                repository_url: https://test.pypi.org/legacy/